/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JComboBox;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.select.Elements;

/**
 *
 * @author agus
 */
public class Noticias extends javax.swing.JFrame {
    private Elements noticiastitu,noticiasinfo;
    int elejida=0;
    String infos[]= new String[12];
    String eleccion;

    
    public HashMap<String, String> pagsnoti = new HashMap<String, String>(){
    {
      put("Liga Argentina","http://www.marca.com/futbol/futbol_internacional/argentina.html?cid=MENUDES3601&s_kw=america_argentina");  
      put("Liga BBVA","http://www.marca.com/futbol/1adivision.html");  
      put("Premier League","http://www.marca.com/futbol/futbol_internacional/premier_league.html");  
      put("Serie A","http://www.marca.com/futbol/futbol_internacional/calcio.html");  
      put("Bundesliga","http://www.marca.com/futbol/futbol_internacional/bundesliga.html");  
    }
};
    
    /**
     * Creates new form Noticias
     */
    public Noticias() {
        initComponents();
        initCmboxliga();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnback = new javax.swing.JButton();
        cmbliga = new javax.swing.JComboBox();
        labeltitu = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        info = new javax.swing.JTextArea();
        btnant = new javax.swing.JButton();
        btnsig = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnback.setBackground(java.awt.Color.black);
        btnback.setForeground(java.awt.Color.white);
        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        getContentPane().add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 140, 60, 30));

        cmbliga.setBackground(java.awt.Color.white);
        cmbliga.setForeground(java.awt.Color.black);
        cmbliga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbligaActionPerformed(evt);
            }
        });
        cmbliga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbligaKeyPressed(evt);
            }
        });
        getContentPane().add(cmbliga, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 180, -1));

        labeltitu.setFont(new java.awt.Font("Liberation Mono", 0, 15)); // NOI18N
        labeltitu.setForeground(java.awt.Color.white);
        getContentPane().add(labeltitu, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 540, 30));

        info.setColumns(20);
        info.setRows(5);
        info.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                infoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(info);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 950, 75));

        btnant.setBackground(java.awt.Color.black);
        btnant.setForeground(java.awt.Color.white);
        btnant.setText("Anterior");
        btnant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnantActionPerformed(evt);
            }
        });
        getContentPane().add(btnant, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 142, -1, -1));

        btnsig.setBackground(java.awt.Color.black);
        btnsig.setForeground(java.awt.Color.white);
        btnsig.setText("Siguiente");
        btnsig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsigActionPerformed(evt);
            }
        });
        getContentPane().add(btnsig, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 142, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mini2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
                proyect nuevo= new proyect();
                this.setVisible(false);
                nuevo.setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed

    private void cmbligaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbligaActionPerformed
        String selectedElement = (String) cmbliga.getSelectedItem();
        eleccion=selectedElement.toString();
        Document doc;
        
        
        String liga_buscada = null;
        for(Map.Entry<String, String> item: pagsnoti.entrySet()){
            if(item.getKey().equals(selectedElement)){
             liga_buscada= item.getValue();
            }
        }
            try { doc = Jsoup.connect(liga_buscada)
                    .userAgent("Mozilla")
                    .timeout(10000)
                    .get();
                
                noticiastitu=doc.body().getElementsByTag("h2");
                System.out.println(noticiastitu.text());
                noticiasinfo=doc.body().getElementsByTag("p");
                
                int cant= noticiasinfo.size();
                System.out.println(cant);
                int num=0;
                
                if(eleccion.equalsIgnoreCase("Liga BBVA")){
                    for(int i = 0;i<20;i++){
                        if(i!=0 && i%2==0){
                            infos[num]=noticiasinfo.get(i).text();
                            num++;
                        //System.out.println(noticiasinfo.get(i).text());;
                    }
                }
                }else{
                    for(int i = 0;i<24;i++){
                        if(i!=0 && i%2==0){
                            infos[num]=noticiasinfo.get(i).text();
                            num++;
                        }
                    }   
                }
                cargar();
           
            }catch(IOException a){}
    }//GEN-LAST:event_cmbligaActionPerformed

    private void btnantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnantActionPerformed
      back();
    }//GEN-LAST:event_btnantActionPerformed

    private void btnsigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsigActionPerformed
        next();
    }//GEN-LAST:event_btnsigActionPerformed

    private void infoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_infoKeyPressed
         
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            next();
        }
    }//GEN-LAST:event_infoKeyPressed

    private void cmbligaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbligaKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            next();
         }
         if(evt.getKeyCode()==KeyEvent.VK_LEFT){
            back();}
    }//GEN-LAST:event_cmbligaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Noticias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Noticias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Noticias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Noticias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Noticias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnant;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnsig;
    private javax.swing.JComboBox cmbliga;
    private javax.swing.JTextArea info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labeltitu;
    // End of variables declaration//GEN-END:variables

    private void initCmboxliga(){
        cmbliga.removeAllItems();
        for(Map.Entry<String, String> item: pagsnoti.entrySet()){
            cmbliga.addItem(item.getKey());
        }
    }
    
    private void cargar(){
    
        if(eleccion.equalsIgnoreCase("Liga BBVA")){
            for(int i = 0;i<10;i++){
                        if(elejida==i){
                            System.out.println(noticiastitu.get(i).text()+"\n"+infos[i]);
                            labeltitu.setText(noticiastitu.get(i).text());
                            info.setText(infos[i]);
                    }
                }
        }else{
            for(int i = 0;i<12;i++){
                        if(elejida==i){
                            System.out.println(noticiastitu.get(i).text()+"\n"+infos[i]);
                            labeltitu.setText(noticiastitu.get(i).text());
                            info.setText(infos[i]);
                    }
                }
        }
    }
    private void next(){
        if(eleccion.equalsIgnoreCase("Liga BBVA")){
            if(elejida<10)elejida++;
        }
        else{
            if(elejida<12)elejida++;
        }
        cargar();
    }
    private void back(){
          if(elejida>0)--elejida;
        cargar();
        
    }
}    
