/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JList;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.select.Elements;

/**
 *
 * @author Stucky
 */
public class Tablas extends javax.swing.JFrame {
    private Elements pos,puntos;
    public HashMap<String, String> pags = new HashMap<String, String>(){
    {
      put("http://canchallena.lanacion.com.ar/estadisticas/futbol-primera-division/posiciones","30");  
      put("http://canchallena.lanacion.com.ar/estadisticas/futbol-espana/posiciones","20");  
      put("http://canchallena.lanacion.com.ar/estadisticas/futbol-premier-league/posiciones","20");  
      put("http://canchallena.lanacion.com.ar/estadisticas/futbol-italia/posiciones","20");  
      put("http://es.fifa.com/world-match-centre/nationalleagues/nationalleague=germany-bundesliga-2000000019/standings/","20");  
    }
};
    /**
     * Creates new form Tablas
     */
    public Tablas() {
        initComponents();
        cargarPuntos();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnback = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listargen = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listita = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        listpremi = new javax.swing.JList();
        jScrollPane6 = new javax.swing.JScrollPane();
        listbunde = new javax.swing.JList();
        jScrollPane7 = new javax.swing.JScrollPane();
        listB = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnback.setBackground(java.awt.Color.black);
        btnback.setForeground(java.awt.Color.white);
        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        getContentPane().add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 380, 60, 30));

        jScrollPane1.setViewportView(listargen);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 50, 220, 358));

        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Puntajes Ligas:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, -1, -1));

        jScrollPane4.setViewportView(listita);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 50, 220, 358));

        jScrollPane5.setViewportView(listpremi);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 50, 220, 358));

        jScrollPane6.setViewportView(listbunde);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 50, 220, 358));

        jScrollPane7.setViewportView(listB);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 50, 220, 358));

        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Liga Argentina:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 27, -1, -1));

        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Serie A:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 27, -1, -1));

        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Premier League:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 27, -1, -1));

        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Bundesliga:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 27, -1, -1));

        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Liga BBVA:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 27, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mini2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
                proyect nuevo= new proyect();
                this.setVisible(false);
                nuevo.setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JList listB;
    private javax.swing.JList listargen;
    private javax.swing.JList listbunde;
    private javax.swing.JList listita;
    private javax.swing.JList listpremi;
    // End of variables declaration//GEN-END:variables

    private void cargarPuntos() {
        Document doc;
        
        for (Map.Entry<String, String> item: pags.entrySet()){
            try { doc = Jsoup.connect(item.getKey())
                    .userAgent("Mozilla")
                    .timeout(10000)
                    .get();
                if ("http://es.fifa.com/world-match-centre/nationalleagues/nationalleague=germany-bundesliga-2000000019/standings/".equalsIgnoreCase(item.getKey())){
                    pos= doc.body().getElementsByClass("team");
                    pos.remove(0);
                    puntos=doc.body().getElementsByClass("pts");
                    puntos.remove(0);
                    System.out.println(pos.text());
                    System.out.println(puntos.text());
                }else{
                    
                    pos= doc.body().getElementsByClass("equipo");
                    puntos=doc.body().getElementsByClass("puntos");
                    System.out.println(pos.text());
                    System.out.println(puntos.text());
                    
                
                }
            }catch(IOException a){}
            
            DefaultListModel prelist = new DefaultListModel();

            if(item.getKey().equalsIgnoreCase("http://es.fifa.com/world-match-centre/nationalleagues/nationalleague=germany-bundesliga-2000000019/standings/")){for (int e=0;e<18;e++){prelist.addElement(pos.get(e).text()+" - "+puntos.get(e).text());};listbunde.setModel(prelist);}else 
            if(item.getKey().equalsIgnoreCase("http://canchallena.lanacion.com.ar/estadisticas/futbol-premier-league/posiciones")){for (int e=0;e<20;e++){prelist.addElement(pos.get(e).text()+" - "+puntos.get(e).text());};listpremi.setModel(prelist);}else 
            if(item.getKey().equalsIgnoreCase("http://canchallena.lanacion.com.ar/estadisticas/futbol-italia/posiciones")){for (int e=0;e<20;e++){prelist.addElement(pos.get(e).text()+" - "+puntos.get(e).text());};listita.setModel(prelist); }else
            if(item.getKey().equalsIgnoreCase("http://canchallena.lanacion.com.ar/estadisticas/futbol-espana/posiciones")){for (int e=0;e<20;e++){prelist.addElement(pos.get(e).text()+" - "+puntos.get(e).text());};listB.setModel(prelist); }else
            if(item.getKey().equalsIgnoreCase("http://canchallena.lanacion.com.ar/estadisticas/futbol-primera-division/posiciones")){for (int e=0;e<30;e++){prelist.addElement(pos.get(e).text()+" - "+puntos.get(e).text());};listargen.setModel(prelist); }
             
            }
        }
        
        
    }


